Add PHP Lint check to pre-commit-hook

diff --git a/pre-commit-hook b/pre-commit-hook
--- a/pre-commit-hook
+++ b/pre-commit-hook
@@ -80,3 +80,14 @@ Commit aborted!
 EOF
 	exit 2
 fi
+
+## Lint checks
+# PHP lint
+PHP_EXT="\.php$|\.thtml$"
+FAILED_LINT=$(git diff-index --cached --name-only HEAD | egrep "$PHP_EXT" | xargs --replace -n 1 sh -c 'php -l "{}" > /dev/null 2> /dev/null || echo " {}"')
+if [ -n "$FAILED_LINT" ]
+then
+	echo -e "Some input files failed PHP lint, commit aborted: \n$FAILED_LINT"
+	exit 1
+fi
+exit 0
